spin_manifest_version = 2

[application]
name = "silly-demo"
version = "0.1.0"
authors = ["Viktor Farcic <viktor@farcic.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "silly-demo"

[component.silly-demo]
source = "main.wasm"
allowed_outbound_hosts = []
[component.silly-demo.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
